name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-and-validate:
    name: Lint and Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0  # Adjust to your Terraform version

      - name: Configure Terraform Credentials
        run: |
            mkdir -p $HOME/.terraform.d
            echo "credentials \"app.terraform.io\" {token = \"$TFE_TOKEN\"}" > $HOME/.terraform.d/credentials.tfrc.json
        env:
            TFE_TOKEN: ${{ secrets.TFE_TOKEN }}

      - name: Terraform Init
        run: terraform init
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}

      - name: Terraform Validate
        run: terraform validate

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Terraform Lint
        run: |
          tflint

  terraform-cloud-plan:
    name: Terraform Plan on Terraform Cloud
    runs-on: ubuntu-latest
    needs: [lint-and-validate]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0

      - name: Configure Terraform Credentials
        run: |
            mkdir -p $HOME/.terraform.d
            echo "credentials \"app.terraform.io\" {token = \"$TFE_TOKEN\"}" > $HOME/.terraform.d/credentials.tfrc.json
        env:
            TFE_TOKEN: ${{ secrets.TFE_TOKEN }}

      - name: Terraform Init
        run: terraform init -upgrade
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
          TERRAFORM_CLOUD_ORG: ${{ secrets.TERRAFORM_CLOUD_ORG }}
          TERRAFORM_WORKSPACE_ID: ${{ secrets.TERRAFORM_WORKSPACE_ID }}

      - name: Terraform Cloud Plan
        run: terraform plan
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
          TERRAFORM_CLOUD_ORG: ${{ secrets.TERRAFORM_CLOUD_ORG }}
          TERRAFORM_WORKSPACE_ID: ${{ secrets.TERRAFORM_WORKSPACE_ID }}

  trigger-terraform-cloud:
    name: Trigger Terraform Cloud Apply
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0

      - name: Configure Terraform Credentials
        run: |
            mkdir -p $HOME/.terraform.d
            echo "credentials \"app.terraform.io\" {token = \"$TFE_TOKEN\"}" > $HOME/.terraform.d/credentials.tfrc.json
        env:
            TFE_TOKEN: ${{ secrets.TFE_TOKEN }}

      - name: Terraform Init
        run: terraform init -upgrade
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
          TERRAFORM_CLOUD_ORG: ${{ secrets.TERRAFORM_CLOUD_ORG }}
          TERRAFORM_WORKSPACE_ID: ${{ secrets.TERRAFORM_WORKSPACE_ID }}

      - name: Terraform Cloud Apply
        run: terraform apply -auto-approve
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
          TERRAFORM_CLOUD_ORG: ${{ secrets.TERRAFORM_CLOUD_ORG }}
          TERRAFORM_WORKSPACE_ID: ${{ secrets.TERRAFORM_WORKSPACE_ID }}
